/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 0
 * @maxItems 4
 */
export type ActiveRunNextRuns =
	| []
	| [string]
	| [string, unknown]
	| [string, unknown, unknown]
	| [string, unknown, unknown, unknown];
