/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	API_URL: string;
	API_TOKEN?: string;
	API_USERNAME: string;
	API_PASSWORD: string;
	API_SCHEDULE_ID: string;
	API_EVENT_ID: string;
}
